### ISSUE TITLE
useview_feedback's Unique index not unique enough

### ISSUE THREAD

**Issue by yrimal** [medic/cht-couch2pg#103]
The following combination turned out insufficient for the index to be unique and because of this, materialized views refresh will be failed. 

https://github.com/medic/cht-couch2pg/blob/3e38727075c0132fad3f3e41c4a4461b202519de/libs/medic-users-meta/migrations/202102191153.do.54-create-couchdb-users-meta-table.sql#L18

One example of this case where same user had feedback doc created at same time is PIH_Malawi. There can be other instances as well. 

CC: @garethbowen . 

Also, when we are working on this, we can work #102 together.

**Comment by derickl** [comment]
Do the duplicates have the same device id?

**Comment by mrsarm** [comment]
@yrimal that version of the schema comes from the version 3.2.0 or 3.2.1, but the last version 3.3.0 fixed that, this is the index now: https://github.com/medic/cht-couch2pg/blob/3e38727075c0132fad3f3e41c4a4461b202519de/libs/medic-users-meta/migrations/202105171933.do.86.usersMeta.sql#L22

Looks like the same but notice that the unique constrains was removed. Upgrading to cht-couch2pg 3.3.0, the schema changes will be updated recreating the whole view and related indexes, so if you have a bunch of records better to run the upgrade when the data is little or not used.

**Comment by mrsarm** [comment]
BTW this is the original issue: https://github.com/medic/cht-couch2pg/issues/86
