### ISSUE TITLE
Add timestamp to couchdb table on insert

### ISSUE THREAD

**Issue by aidan-plenert-macdonald** [medic/cht-couch2pg#110]
Currently, there is no timestamp for when a doc is inserted into the `couchdb` table.

We should have a timestamp so we can determine which records were inserted when.

```
CREATE TABLE couchdb (
  doc jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
```

**Comment by mrsarm** [comment]
Question: what is the added value on this? all the records has a timestamp of when they were created or edited for the last time in Couch (and therefore the same data is available as a JSON field in the column `doc`).

The day the record was inserted in PG is not the same, but not sure what could be a use case. If there is one, could be also useful when was updated for the last time in PG?
