### ISSUE TITLE
Tags and Commits to `main` not pushing new images to Docker Hub

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-couch2pg#119]
The reason commits to `main` are failing is because we're checking for the `master` branch [in CI](https://github.com/medic/cht-couch2pg/blob/9117634f5720b1401dea9b2c7bdacb54ea114ce0/.github/workflows/ci.yml#L56) instead of `main`.  When we fix this, we should also fix the [name of the image in the compose file](https://github.com/medic/cht-couch2pg/blob/9117634f5720b1401dea9b2c7bdacb54ea114ce0/docker-compose.yml#L21) to be like `main-node-10` as the new images won't use the old repo default brand like they used to with `master-node-10`

Also, tags that are added are not pushing a new image either - this is a mystery as to why?! Here's an [example of this failing](https://github.com/medic/cht-couch2pg/actions/runs/1965865170).

**Comment by mrjones-plip** [comment]
@eljhkrr - Feel like doing one more round of user acceptance testing?  Now that we know the docker image works, this PR publishes it to docker hub and updates the compose file to use the now renamed image.

To test:
1. `git checkout main&&git pull origin`  to get latest code.  You can check you got the latest compose file with: `grep 'medicmobile/cht-couch2pg:main-node-10' docker-compose.yml` (should show 1 line)
2. Run the same command as before with, using your `COUCHDB_URL` value instead of mine: `COUCHDB_URL=https://medic:password@192-168-68-26.my.local-ip.co:8442/medic docker-compose up`

thanks thanks!

**Comment by mrjones-plip** [comment]
@Hareet - Do you know how tags are supposed to work? I tried [pushing a tag and it failed](https://github.com/medic/cht-couch2pg/actions/runs/1971640319) :( 

if you're not worried about it, no biggie - i'll just close this ticket b/c pushes to `main` [now generate new images](https://hub.docker.com/layers/medicmobile/cht-couch2pg/main-node-10/images/sha256-307c1837778a72fc482906626c05e6bb4b6f0014de8172f204f49bf09d3667eb?context=explore) per [this PR](https://github.com/medic/cht-couch2pg/pull/121).

**Comment by eljhkrr** [comment]
Confirmed it's working well.

**Comment by mrjones-plip** [comment]
Awesome - thanks @eljhkrr !

**Comment by mrjones-plip** [comment]
I dug up the Docker Hub admin credentials in the password safe and manually pushed the readme change there.  

With [eljhkrr](https://github.com/eljhkrr)'s sign off and no other concerns, I'm closing this ticket.  Feel free to re-open if need be!
