### ISSUE TITLE
Sync users database to Postgres

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-couch2pg#137]
A common failure in CHT is that the roles in the `users` database do not match the `user-settings` database. We'd like to write assertions to detect these cases via cht-app-monitoring-data-ingest and request the user document in Postgres. https://github.com/medic/cht-app-monitoring-data-ingest/issues/64

**Comment by garethbowen** [comment]
I'm a little concerned about the security implications of replicating the encrypted passwords. It's not dire, but still less than ideal. Is there another way to expose/detect these errors? Is there a way to have CHT automatically fix this issue rather than being a manual step? How does this error present?

**Comment by kennsippell** [comment]
Discussed the security implications of this today with @mrjones-plip. I'll defer to him re security talk.

We detect these issues today through [scripts like this](https://github.com/medic/cht-pih-malawi-app/blob/main/scripts/detect-user-oddities.js). They are run manually. We are trying to integrate this with monitoring efforts like watchdog.

My understanding is that some parts of CHT use the _users database to determine a user's role and permissions (CouchDB/API/etc), while others use the user-settings doc in medic to determine the user's roles and permissions (webapp). These fall out of sync quite often (eg. I saw it twice last week [example](https://github.com/medic/config-muso/issues/987#issuecomment-1587832887)).  

Also the facility_id can be out of sync between the two.

I don't have a clear summary of how this manifests when roles are not aligned -- but I'd summarize it as "likely general spookiness".

**Comment by garethbowen** [comment]
Would you mind raising an issue in cht-core for the bug (as well as continuing with monitoring)? Essentially cht-core should consistently use the one in user-settings because that's the only one that's downloaded for offline use. However I suspect couchdb db level permissions will use the one in the _users db because that's the only one it knows about. The CHT has code to keep these in sync but obviously it's not working correctly.

**Comment by kennsippell** [comment]
I've opened https://github.com/medic/cht-core/issues/8337.

> as well as continuing with monitoring

Can you clarify what you mean here? Are you saying you have no blocking security concerns here and I should proceed to sync _users db to Postgres? Or are you saying we should continue to manually monitor this + address a fix for it in core?

**Comment by mrjones-plip** [comment]
>> I'm a little concerned about the security implications of replicating the encrypted passwords. It's not dire, but still less than ideal.
>
> Discussed the security implications of this today with @mrjones-plip. I'll defer to him re security talk.

Yes, agreed this is not ideal and should be done with care (not on by default).  Some thoughts on why this seemed OK (enough):
* Passwords are hashed (not encrypted) with pbkdf2 (@kennsippell  and @eljhkrr: sorry I said bcrypt on our call today - I was wrong!).  This is a [ modern hashing algorithm and considered secure](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html)
* The Postgres DB (RDBMs in Medic's case) or is already full of PII and PHI and is considered a safe place to put sensitive data, like these hashes
* The admin credentials the CHT instance are already on the couch2pg system to facilitate logging in to CouchDB, a fundamental and mandatory function of couch2pg.  If someone illicitly gains access to the system, they'll gain access to the admin password and they wouldn't bother with the user account hashes when the admin password is right there in plaintext.

A low cost remediation here would be to zero out the hash values in the postgres DB at some point in the sync process.  This won't stop anyone per plaintext credentials above, but is so cheap there's no reason not to do it and it might help just a little.

As an aside, it looks like our `iterations` [on pbkdf2 is low](https://github.com/medic/cht-core/blob/0c7399770fdcb94dbbc1764f25e3141e6b79b5b9/shared-libs/settings/src/index.js#L139), and have [filed an issue accordingly](https://github.com/medic/cht-core/issues/8338).

**Comment by garethbowen** [comment]
> Can you clarify what you mean here?

That the bug fix and monitoring effort should continue in parallel.

**Comment by garethbowen** [comment]
> A low cost remediation here would be to zero out the hash values in the postgres DB at some point in the sync process. This won't stop anyone per plaintext credentials mentioned above, but is so cheap there's no reason not to do it and it might help just a little.

This is the solution I was thinking of. If it's a low effort change it would make me feel better to know we're not storing the hashed passwords.

**Comment by kennsippell** [comment]
That will require a change in the underlying couch2pg repository and not just cht-couch2pg. Here is a proposal https://github.com/medic/couch2pg/pull/45. It's maybe a bit loose since it isn't only for the `_users` database.

**Comment by mrjones-plip** [comment]
@kennsippell  - the speed at which you're moving is inspiring (EG PR to strip hashes in what looks like <60 min).  I really appreciate your bold efforts here - thank you!!

**Comment by kennsippell** [comment]
Released as v3.6.2
