### ISSUE TITLE
Architecture v3: couch2pg + postgres

### ISSUE THREAD

**Issue by Hareet** [medic/cht-couch2pg#56]
To satisfy: https://github.com/medic/cht-core/issues/6189

We should initialize Postgres with custom parameters for 1 project.

- CI publishes couch2pg docker image
- docker-compose consists of adding couch2pg + a postgres container to existing medic-net network
- initialization setups up postgres accurately

**Comment by Hareet** [comment]
@yrimal 
There's a lot of people who access our Postgres Server. I want to make sure all the use-cases still function or can be adequately substituted while this is re-architected in a different network. 

Can you describe what you are doing when you access the server (crons, scripts) related to postgres, and what's typical use for partners, since I see a lot of partner type logins present? 

Thanks

**Comment by yrimal** [comment]
Hi @Hareet ,
For impact monitoring, impact team creates certain views and functions on each database. It's not always the same query for all database so we can't containerize it. Once impact functions have been installed on these databases, we've a dblink connection set from `dwh_impact` database that queries every databases to pull updated data every other night. 

Apart from this, when there's a need to query database for other purposes, then also we need to access those databases.

**Comment by yrimal** [comment]
For partner users, only some (probably just lg) have direct access to the database. But, at least one account will still need access from klipfolio for partner facing dashboards. If things are not clear, I can talk over call as well.

**Comment by Hareet** [comment]
Testing:
- [ ] Be able docker-compose medic-os container or arch v3 containers (docker-compose)
- [ ] Launch couch2pg + postgres containers after medic-os is initiliazed, and verify data is inserted to postgres
- [ ] Entrypoints work in restarts, crashes and initial setup

**Comment by Hareet** [comment]
We have labeled this ticket as 5 points for SRE Sprint 2

Unable to share medic-infrastructure labels with this repo.

**Comment by Hareet** [comment]
completed!
